#ifndef __SLIC3R_VERSION_H
#define __SLIC3R_VERSION_H

#define SLIC3R_APP_NAME "@SLIC3R_APP_NAME@"
#define SLIC3R_APP_KEY "@SLIC3R_APP_KEY@"
#define SLIC3R_VERSION "@SLIC3R_VERSION@"
#define SLIC3R_BUILD_ID "@SLIC3R_BUILD_ID@"

#endif /* __SLIC3R_VERSION_H */
