version: 2
updates:
  # Only care about major updates to github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore: # Only suggest major updates for built-in actions
      - dependency-name: "github/*"
        update-types: ["version-update:semver-patch", "version-update:semver-minor"]
      - dependency-name: "actions/*"
        update-types: ["version-update:semver-patch", "version-update:semver-minor"]
  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
  # no support for c/cpp
