name: 🚀 Feature Request / Enhancement
description: Suggest an improvement to make Orca Slicer even better!
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!

        If your idea is still at the formulation stage, or you're not sure it would
        be useful to many users, you can raise it as a discussion topic under [Ideas](https://github.com/SoftFever/OrcaSlicer/discussions/categories/ideas)
        or you can raise it on the [Discord server](https://discord.gg/P4VE9UY9gJ).
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this feature request?
      description: |
        Please search to see if an issue already exists for a feature, or perhaps one similar.
        You can then comment and react so that we know know much interest there is in the feature request.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when [...]
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Which printers will be beneficial to this feature?
      description: Select affected printer firmware type.
      multiple: true
      options: 
        - Klipper
        - Marlin
        - Others
        - All
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: It should do [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: |
        1. [...]
        2. [...]
        3. [...]
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Add any other context, diagrams, illustations or screenshots about the feature request here.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
