#!/bin/bash
# these are the Clear Linux specific build functions
export FOUND_GTK3
FOUND_GTK3=$(find /usr/lib64/libgtk-3.so.* 2>/dev/null | tail -n 1 || true)

# Addtional bundles for OrcaSlicer
export REQUIRED_BUNDLES=(
    c-basic
    dev-utils
    devpkg-curl
    devpkg-glew
    devpkg-glu
    devpkg-gstreamer
    devpkg-gtk3
    devpkg-libmspack
    devpkg-libsecret
    devpkg-openssl
    devpkg-webkitgtk
    file
    git
    lib-opengl
    perl-basic
    texinfo
    wget
)

if [[ -n "$UPDATE_LIB" ]]
then
    echo "Updating linux ..."
    echo swupd bundle-add -y "${REQUIRED_BUNDLES[@]}"
    echo -e "done\n"
    exit 0
fi

export FOUND_GTK3_DEV
FOUND_GTK3_DEV=$(find /usr/lib64/libgtk-3.so 2>/dev/null || true)
