#!/bin/bash

REQUIRED_DEV_PACKAGES=(
    autoconf
    automake
    cmake
    dbus-devel
    eglexternalplatform-devel
    extra-cmake-modules
    file
    gcc
    gcc-c++
    gettext
    git
    gstreamer1-devel
    gstreamermm-devel
    gtk3-devel
    libmspack-devel
    libquadmath-devel
    libsecret-devel
    libspnav-devel
    libtool
    m4
    mesa-libGLU-devel
    ninja-build
    openssl-devel
    perl-FindBin
    texinfo
    wayland-protocols-devel
    webkit2gtk4.0-devel
    wget
    libcurl-devel
)

if [[ -n "$UPDATE_LIB" ]]
then
    NEEDED_PKGS=()
    for PKG in "${REQUIRED_DEV_PACKAGES[@]}"; do
        rpm -q "${PKG}" > /dev/null || NEEDED_PKGS+=("${PKG}")
    done

    if [[ "${#NEEDED_PKGS[*]}" -gt 0 ]]; then
        sudo dnf install -y "${NEEDED_PKGS[@]}"
    fi
    echo -e "done\n"
    exit 0
fi

export FOUND_GTK3_DEV
FOUND_GTK3_DEV=$(rpm -qa | grep -P '^gtk3-devel' || true)
